name: payvice_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  itex_pay:
    git: https://github.com/bolaware/itex-pay
  flutter_svg: ^0.23.0
  app_settings: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  flutter_easyloading: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_sim_country_code: ^0.1.1
  pin_code_text_field: ^1.8.0
  country_code_picker: ^2.0.2
  firebase_core: 1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^10.0.7
  http: ^0.13.3
  grouped_buttons: ^1.0.4
  shared_preferences: ^2.0.8
  device_info: ^2.0.2
  local_auth: ^1.1.8
  flutter_secure_storage: ^4.2.1
  toast: ^0.1.5
  fbroadcast: ^1.1.1
  permission_handler: ^8.3.0
  flutter_toggle_tab: ^1.1.4
  contacts_service: ^0.6.1
  dotted_border: 2.0.0
  flutter_masked_text: ^0.8.0
  rxdart: ^0.27.2
  intl: ^0.17.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1
  share_files_and_screenshot_widgets: ^1.0.6
  image_picker: ^0.8.4+5
  flutter_html: ^2.2.1
  flutter_slidable: ^1.2.0
  overlay_support: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: PayviceIcons
      fonts:
        - asset: fonts/PayviceIcons.ttf
    - family: NeurialGrotesk
      fonts:
        - asset: fonts/NeurialGrotesk-Regular.otf
        - asset: fonts/NeurialGrotesk-Medium.otf
        - asset: fonts/NeurialGrotesk-Bold.otf